import { useState } from 'react';
import { useCampaignStore } from '../store/campaignStore';
import { Copy, RefreshCw, Save, Trash2, Sparkles, Check } from 'lucide-react';
import Anthropic from '@anthropic-ai/sdk';

const PITCH_CATEGORIES = [
  {
    id: 'social-media',
    label: 'Social Media DMs',
    subTypes: [
      { id: 'instagram-dm', label: 'Instagram DM' },
      { id: 'tiktok-dm', label: 'TikTok DM' },
      { id: 'facebook-dm', label: 'Facebook DM' },
      { id: 'twitter-dm', label: 'Twitter/X DM' },
      { id: 'linkedin-dm', label: 'LinkedIn DM' }
    ]
  },
  {
    id: 'emails',
    label: 'Emails',
    subTypes: [
      { id: 'cold-email', label: 'Cold Email' },
      { id: 'partnership-inquiry', label: 'Partnership Inquiry Email' },
      { id: 'rate-card-email', label: 'Rate Card Email' },
      { id: 'collaboration-proposal', label: 'Collaboration Proposal Email' }
    ]
  },
  {
    id: 'follow-up',
    label: 'Follow Up',
    subTypes: [
      { id: 'follow-up-no-response', label: 'Follow Up After No Response' },
      { id: 'follow-up-positive', label: 'Follow Up After Positive Reply' },
      { id: 'follow-up-ghosted', label: 'Follow Up After Being Ghosted' },
      { id: 'chase-payment', label: 'Chase for Payment' }
    ]
  },
  {
    id: 'rate-negotiation',
    label: 'Rate Negotiation',
    subTypes: [
      { id: 'counter-offer', label: 'Counter Offer' },
      { id: 'rate-increase', label: 'Rate Increase Request' },
      { id: 'package-upsell', label: 'Package Upsell' },
      { id: 'usage-rights-negotiation', label: 'Usage Rights Negotiation' }
    ]
  }
] as const;

type PitchType = string;

interface SavedPitch {
  id: string;
  brandName: string;
  type: string;
  content: string;
  preview: string;
  date: string;
}

export default function PitchGenerator() {
  const { ugcSelectedNiche, contentCategory, portfolioLink } = useCampaignStore();

  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [selectedSubType, setSelectedSubType] = useState<string | null>(null);
  const [pitchInputs, setPitchInputs] = useState({
    brandName: '',
    brandNiche: '',
    creatorNiche: ugcSelectedNiche || contentCategory || '',
    contentStyle: '',
    portfolioLink: portfolioLink || '',
    specificOffer: '',
    daysSinceFirstPitch: '',
    previousResponse: '',
    offeredRate: '',
    desiredRate: '',
    valueReason: ''
  });
  const [generatedPitch, setGeneratedPitch] = useState<{ type: string; brand: string; content: string; wordCount: number } | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [savedPitches, setSavedPitches] = useState<SavedPitch[]>([]);
  const [copied, setCopied] = useState(false);

  const getWordCount = (text: string) => {
    return text.trim().split(/\s+/).length;
  };

  const getWordLimits = (type: string) => {
    if (type.includes('email')) return 100;
    if (type.includes('dm')) return 50;
    if (type.includes('follow-up')) return 60;
    if (type.includes('negotiation') || type.includes('counter') || type.includes('rate')) return 120;
    return 80;
  };

  const getWordCountColor = (count: number, limit: number) => {
    if (count < limit) return '#22c55e';
    if (count === limit) return '#c9a84c';
    return '#ef4444';
  };

  const generatePitch = async () => {
    if (!pitchInputs.brandName) {
      alert('Please enter the brand name');
      return;
    }

    setIsGenerating(true);

    try {
      const apiKey = import.meta.env.VITE_ANTHROPIC_API_KEY;
      if (!apiKey) {
        throw new Error('Anthropic API key not found');
      }

      const anthropic = new Anthropic({
        apiKey,
        dangerouslyAllowBrowser: true
      });

      const systemPrompt = `You are Velour's AI pitch coach. You are generating a personalised outreach pitch for a UGC creator. Your job is to write a pitch that gets a real response from a real brand - not a pitch that sounds like it was generated by AI or copy pasted from a template.

Every pitch must follow these four rules invisibly:

Rule 1 - Be specific:
Reference the brand by name. Reference something real about their product category or content style. Generic pitches get deleted in under 3 seconds. Specific pitches make the brand feel chosen.

Rule 2 - Be brief:
Cold Email: maximum 100 words in the body. If it is longer cut it in half.
Instagram DM: maximum 50 words. One thought per sentence.
LinkedIn Message: maximum 80 words. Professional but human.
Follow Up: maximum 60 words. Reference the original pitch. Make it easy to say yes.
Rate Negotiation: maximum 120 words. Lead with value then state the number confidently.

Rule 3 - Lead with value:
Open with what you can do for the brand - not who you are. The brand does not care about your passion. They care about what their content will look like after working with you.

Rule 4 - Always include proof:
The portfolio link must appear naturally in every pitch. Never as an afterthought. Always as the obvious next step for the brand to take.

Tone calibration by pitch type:
Cold Email - professional, warm, direct. Sounds like a peer reaching out not a salesperson.
Instagram DM - casual, punchy, conversational. Feels like a genuine message not a pitch.
LinkedIn Message - polished, confident, business-first. Shows the creator understands the professional context.
Follow Up - light touch, no pressure, easy yes. Acknowledges busy inboxes without being apologetic.
Rate Negotiation - calm, confident, value-led. Never apologetic about the number. States the rate as a fact not a question.

Output format:
For Cold Email: subject line first on its own line starting with "Subject:", then a blank line, then body copy
For all others: body copy only

Never use: passionate, love what you do, huge fan, would love to, reach out, just wanted to, hope this finds you well, I came across your brand
Never sound like AI generated content
Never open with I
Generate completely original content every time - never repeat a previous pitch structure`;

      const selectedCat = PITCH_CATEGORIES.find(c => c.id === selectedCategory);
      const selectedSub = selectedCat?.subTypes.find(s => s.id === selectedSubType);
      const pitchLabel = selectedSub?.label || 'pitch';

      let userPrompt = `Generate a ${pitchLabel} pitch with these details:

Brand name: ${pitchInputs.brandName}
Brand niche/product type: ${pitchInputs.brandNiche || 'not specified'}
Creator niche: ${pitchInputs.creatorNiche}
Content style: ${pitchInputs.contentStyle || 'authentic UGC content'}
Portfolio link: ${pitchInputs.portfolioLink}`;

      if (selectedSubType?.includes('email') && pitchInputs.specificOffer) {
        userPrompt += `\nWhat to create for them: ${pitchInputs.specificOffer}`;
      }

      if (selectedCategory === 'follow-up') {
        userPrompt += `\nDays since first pitch: ${pitchInputs.daysSinceFirstPitch || 'about a week'}`;
        if (pitchInputs.previousResponse) {
          userPrompt += `\nTheir response: ${pitchInputs.previousResponse}`;
        }
      }

      if (selectedCategory === 'rate-negotiation') {
        userPrompt += `\nRate they offered: ${pitchInputs.offeredRate}`;
        userPrompt += `\nRate you want: ${pitchInputs.desiredRate}`;
        userPrompt += `\nWhy you are worth it: ${pitchInputs.valueReason}`;
      }

      const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: userPrompt
        }],
        system: systemPrompt
      });

      const content = message.content[0].type === 'text' ? message.content[0].text : '';
      const wordCount = getWordCount(content);

      setGeneratedPitch({
        type: selectedSubType || '',
        brand: pitchInputs.brandName,
        content,
        wordCount
      });
    } catch (error) {
      console.error('Error generating pitch:', error);
      alert('Failed to generate pitch. Please check your API key and try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const copyPitch = () => {
    if (generatedPitch) {
      navigator.clipboard.writeText(generatedPitch.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const savePitch = () => {
    if (generatedPitch) {
      const newPitch: SavedPitch = {
        id: Date.now().toString(),
        brandName: generatedPitch.brand,
        type: generatedPitch.type,
        content: generatedPitch.content,
        preview: generatedPitch.content.substring(0, 80) + '...',
        date: new Date().toLocaleDateString()
      };
      setSavedPitches([newPitch, ...savedPitches]);
    }
  };

  const deletePitch = (id: string) => {
    setSavedPitches(savedPitches.filter(p => p.id !== id));
  };

  const copyFromLibrary = (content: string) => {
    navigator.clipboard.writeText(content);
  };

  const getPitchTypeLabel = (typeId: string) => {
    for (const category of PITCH_CATEGORIES) {
      const subType = category.subTypes.find(s => s.id === typeId);
      if (subType) return subType.label;
    }
    return typeId;
  };

  const handleCategorySelect = (categoryId: string) => {
    if (selectedCategory === categoryId) {
      setSelectedCategory(null);
      setSelectedSubType(null);
    } else {
      setSelectedCategory(categoryId);
      setSelectedSubType(null);
    }
  };

  const handleSubTypeSelect = (subTypeId: string) => {
    setSelectedSubType(subTypeId);
  };

  const selectedCategoryObj = PITCH_CATEGORIES.find(c => c.id === selectedCategory);
  const canGenerate = pitchInputs.brandName && selectedCategory && selectedSubType;

  return (
    <div style={{ paddingBottom: '80px' }}>
      <h1 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '42px', fontWeight: 600, color: '#f0ebff', marginBottom: '12px' }}>
        Generate Pitches That Get Responses
      </h1>
      <p style={{ fontSize: '14px', fontStyle: 'italic', color: '#c9a84c', marginBottom: '48px' }}>
        Every pitch is personalised to the brand you are targeting. No generic templates. No copy paste. Just pitches that convert.
      </p>

      {/* Section 1: Choose Your Pitch Type */}
      <div style={{ marginBottom: '48px' }}>
        <h2 style={{ fontSize: '24px', fontWeight: 700, color: '#f0ebff', marginBottom: '20px', fontFamily: 'Cormorant Garamond, serif' }}>
          Section 1 - Choose Your Pitch Type
        </h2>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', marginBottom: '24px' }}>
          {PITCH_CATEGORIES.map((category) => (
            <button
              key={category.id}
              onClick={() => handleCategorySelect(category.id)}
              style={{
                padding: '12px 24px',
                background: selectedCategory === category.id ? 'linear-gradient(135deg, #c9a84c, #8B6914)' : 'rgba(255,255,255,0.05)',
                border: selectedCategory === category.id ? 'none' : '1px solid rgba(255,255,255,0.1)',
                borderRadius: '100px',
                color: selectedCategory === category.id ? '#0a0610' : '#d4cee8',
                fontSize: '14px',
                fontWeight: 600,
                cursor: 'pointer',
                transition: 'all 0.2s',
                boxShadow: selectedCategory === category.id ? '0 4px 12px rgba(201,168,76,0.4)' : 'none',
              }}
            >
              {category.label}
            </button>
          ))}
        </div>

        {selectedCategoryObj && (
          <div>
            <p style={{ fontSize: '12px', fontWeight: 700, color: '#c9a84c', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '12px' }}>
              Select Type:
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
              {selectedCategoryObj.subTypes.map((subType) => (
                <button
                  key={subType.id}
                  onClick={() => handleSubTypeSelect(subType.id)}
                  style={{
                    padding: '10px 20px',
                    background: selectedSubType === subType.id ? 'linear-gradient(135deg, #c9a84c, #8B6914)' : 'rgba(255,255,255,0.03)',
                    border: selectedSubType === subType.id ? 'none' : '1px solid rgba(255,255,255,0.08)',
                    borderRadius: '100px',
                    color: selectedSubType === subType.id ? '#0a0610' : '#d4cee8',
                    fontSize: '13px',
                    fontWeight: 600,
                    cursor: 'pointer',
                    transition: 'all 0.2s',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px',
                    boxShadow: selectedSubType === subType.id ? '0 2px 8px rgba(201,168,76,0.3)' : 'none',
                  }}
                >
                  {selectedSubType === subType.id && <Check size={14} />}
                  {subType.label}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Section 2: Tell Velour About This Pitch */}
      <div style={{ marginBottom: '48px' }}>
        <h2 style={{ fontSize: '24px', fontWeight: 700, color: '#f0ebff', marginBottom: '20px', fontFamily: 'Cormorant Garamond, serif' }}>
          Section 2 - Tell Velour About This Pitch
        </h2>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <input
            type="text"
            placeholder="Brand name you are pitching to *"
            value={pitchInputs.brandName}
            onChange={(e) => setPitchInputs({ ...pitchInputs, brandName: e.target.value })}
            style={{
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
            }}
          />

          <input
            type="text"
            placeholder="Their niche or product type"
            value={pitchInputs.brandNiche}
            onChange={(e) => setPitchInputs({ ...pitchInputs, brandNiche: e.target.value })}
            style={{
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
            }}
          />

          <input
            type="text"
            placeholder="Your niche"
            value={pitchInputs.creatorNiche}
            onChange={(e) => setPitchInputs({ ...pitchInputs, creatorNiche: e.target.value })}
            style={{
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
            }}
          />

          <input
            type="text"
            placeholder="Your content style"
            value={pitchInputs.contentStyle}
            onChange={(e) => setPitchInputs({ ...pitchInputs, contentStyle: e.target.value })}
            style={{
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
            }}
          />

          <input
            type="url"
            placeholder="Your portfolio link"
            value={pitchInputs.portfolioLink}
            onChange={(e) => setPitchInputs({ ...pitchInputs, portfolioLink: e.target.value })}
            style={{
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
            }}
          />

          {selectedCategory === 'emails' && (
            <input
              type="text"
              placeholder="What specifically do you want to create for them"
              value={pitchInputs.specificOffer}
              onChange={(e) => setPitchInputs({ ...pitchInputs, specificOffer: e.target.value })}
              style={{
                padding: '14px 16px',
                background: 'rgba(201,168,76,0.08)',
                border: '1px solid rgba(201,168,76,0.2)',
                borderRadius: '8px',
                color: '#f0ebff',
                fontSize: '14px',
              }}
            />
          )}

          {selectedCategory === 'follow-up' && (
            <>
              <input
                type="text"
                placeholder="How many days since your first pitch"
                value={pitchInputs.daysSinceFirstPitch}
                onChange={(e) => setPitchInputs({ ...pitchInputs, daysSinceFirstPitch: e.target.value })}
                style={{
                  padding: '14px 16px',
                  background: 'rgba(201,168,76,0.08)',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '8px',
                  color: '#f0ebff',
                  fontSize: '14px',
                }}
              />
              <input
                type="text"
                placeholder="What response if any did you get"
                value={pitchInputs.previousResponse}
                onChange={(e) => setPitchInputs({ ...pitchInputs, previousResponse: e.target.value })}
                style={{
                  padding: '14px 16px',
                  background: 'rgba(201,168,76,0.08)',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '8px',
                  color: '#f0ebff',
                  fontSize: '14px',
                }}
              />
            </>
          )}

          {selectedCategory === 'rate-negotiation' && (
            <>
              <input
                type="text"
                placeholder="What rate did they offer"
                value={pitchInputs.offeredRate}
                onChange={(e) => setPitchInputs({ ...pitchInputs, offeredRate: e.target.value })}
                style={{
                  padding: '14px 16px',
                  background: 'rgba(201,168,76,0.08)',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '8px',
                  color: '#f0ebff',
                  fontSize: '14px',
                }}
              />
              <input
                type="text"
                placeholder="What rate you want"
                value={pitchInputs.desiredRate}
                onChange={(e) => setPitchInputs({ ...pitchInputs, desiredRate: e.target.value })}
                style={{
                  padding: '14px 16px',
                  background: 'rgba(201,168,76,0.08)',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '8px',
                  color: '#f0ebff',
                  fontSize: '14px',
                }}
              />
              <input
                type="text"
                placeholder="Why you are worth the difference - one line"
                value={pitchInputs.valueReason}
                onChange={(e) => setPitchInputs({ ...pitchInputs, valueReason: e.target.value })}
                style={{
                  padding: '14px 16px',
                  background: 'rgba(201,168,76,0.08)',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '8px',
                  color: '#f0ebff',
                  fontSize: '14px',
                }}
              />
            </>
          )}
        </div>
      </div>

      {/* Section 3: Generate */}
      <div style={{ marginBottom: '48px' }}>
        <button
          onClick={generatePitch}
          disabled={isGenerating || !canGenerate}
          style={{
            padding: '16px 32px',
            background: isGenerating || !canGenerate ? 'rgba(201,168,76,0.5)' : 'linear-gradient(135deg, #c9a84c, #8B6914)',
            color: '#0a0610',
            border: 'none',
            borderRadius: '100px',
            fontSize: '16px',
            fontWeight: 700,
            cursor: isGenerating || !canGenerate ? 'not-allowed' : 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
            opacity: !canGenerate ? 0.5 : 1,
          }}
        >
          <Sparkles size={18} />
          {isGenerating ? 'Generating...' : 'Generate My Pitch'}
        </button>
      </div>

      {/* Generated Pitch Output */}
      {generatedPitch && (
        <div style={{ marginBottom: '48px' }}>
          <div
            style={{
              background: '#1c1a35',
              border: '2px solid #c9a84c',
              borderRadius: '16px',
              padding: '32px',
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' }}>
              <div>
                <span
                  style={{
                    display: 'inline-block',
                    padding: '6px 16px',
                    background: 'linear-gradient(135deg, #c9a84c, #8B6914)',
                    color: '#0a0610',
                    borderRadius: '100px',
                    fontSize: '12px',
                    fontWeight: 700,
                    marginBottom: '12px',
                  }}
                >
                  {getPitchTypeLabel(generatedPitch.type)}
                </span>
                <h3 style={{ fontSize: '24px', fontWeight: 700, color: '#e8c96a', margin: 0 }}>
                  {generatedPitch.brand}
                </h3>
              </div>
              <div
                style={{
                  fontSize: '14px',
                  fontWeight: 600,
                  color: getWordCountColor(generatedPitch.wordCount, getWordLimits(generatedPitch.type as PitchType)),
                }}
              >
                {generatedPitch.wordCount} words
              </div>
            </div>

            <div
              style={{
                background: 'rgba(0,0,0,0.2)',
                borderRadius: '8px',
                padding: '20px',
                marginBottom: '20px',
              }}
            >
              <pre
                style={{
                  fontSize: '14px',
                  color: '#d4cee8',
                  lineHeight: 1.8,
                  margin: 0,
                  fontFamily: 'inherit',
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                }}
              >
                {generatedPitch.content}
              </pre>
            </div>

            <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
              <button
                onClick={copyPitch}
                style={{
                  padding: '12px 24px',
                  background: copied ? 'rgba(34,197,94,0.2)' : 'rgba(255,255,255,0.1)',
                  border: copied ? '1px solid #22c55e' : '1px solid rgba(255,255,255,0.2)',
                  borderRadius: '100px',
                  color: copied ? '#22c55e' : '#f0ebff',
                  fontSize: '14px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                }}
              >
                <Copy size={16} />
                {copied ? 'Copied!' : 'Copy'}
              </button>

              <button
                onClick={generatePitch}
                style={{
                  padding: '12px 24px',
                  background: 'rgba(255,255,255,0.1)',
                  border: '1px solid rgba(255,255,255,0.2)',
                  borderRadius: '100px',
                  color: '#f0ebff',
                  fontSize: '14px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                }}
              >
                <RefreshCw size={16} />
                Regenerate
              </button>

              <button
                onClick={savePitch}
                style={{
                  padding: '12px 24px',
                  background: 'linear-gradient(135deg, #c9a84c, #8B6914)',
                  border: 'none',
                  borderRadius: '100px',
                  color: '#0a0610',
                  fontSize: '14px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  boxShadow: '0 2px 8px rgba(201,168,76,0.3)',
                }}
              >
                <Save size={16} />
                Save This Pitch
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Pitch Library */}
      {savedPitches.length > 0 && (
        <div>
          <h2 style={{ fontSize: '28px', fontWeight: 700, color: '#f0ebff', marginBottom: '24px', fontFamily: 'Cormorant Garamond, serif' }}>
            Your Saved Pitches
          </h2>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {savedPitches.map((pitch) => (
              <div
                key={pitch.id}
                style={{
                  background: '#1c1a35',
                  border: '1px solid rgba(201,168,76,0.2)',
                  borderRadius: '12px',
                  padding: '20px',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
                  <div>
                    <span
                      style={{
                        display: 'inline-block',
                        padding: '4px 12px',
                        background: 'rgba(201,168,76,0.2)',
                        color: '#c9a84c',
                        borderRadius: '100px',
                        fontSize: '11px',
                        fontWeight: 700,
                        marginBottom: '8px',
                      }}
                    >
                      {getPitchTypeLabel(pitch.type)}
                    </span>
                    <h4 style={{ fontSize: '18px', fontWeight: 700, color: '#e8c96a', margin: 0 }}>
                      {pitch.brandName}
                    </h4>
                  </div>
                  <span style={{ fontSize: '12px', color: '#9b8fb5' }}>{pitch.date}</span>
                </div>

                <p style={{ fontSize: '13px', color: '#d4cee8', marginBottom: '16px', lineHeight: 1.6 }}>
                  {pitch.preview}
                </p>

                <div style={{ display: 'flex', gap: '8px' }}>
                  <button
                    onClick={() => copyFromLibrary(pitch.content)}
                    style={{
                      padding: '8px 16px',
                      background: 'rgba(255,255,255,0.1)',
                      border: '1px solid rgba(255,255,255,0.2)',
                      borderRadius: '100px',
                      color: '#f0ebff',
                      fontSize: '12px',
                      fontWeight: 600,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '4px',
                    }}
                  >
                    <Copy size={14} />
                    Copy
                  </button>

                  <button
                    onClick={() => deletePitch(pitch.id)}
                    style={{
                      padding: '8px 16px',
                      background: 'rgba(239,68,68,0.1)',
                      border: '1px solid rgba(239,68,68,0.3)',
                      borderRadius: '100px',
                      color: '#ef4444',
                      fontSize: '12px',
                      fontWeight: 600,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '4px',
                    }}
                  >
                    <Trash2 size={14} />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
