import { useState, useEffect } from 'react';
import { useCampaignStore } from '../store/campaignStore';
import { CheckCircle2, Circle, ExternalLink, ChevronRight, Folder, Copy, ZoomIn, X } from 'lucide-react';
import portfolioTemplate1 from '../assets/Copy_of_UGC_Portfolio_Template_.jpg';
import portfolioTemplate2 from '../assets/Copy_of_UGC_Portfolio_Template_2.jpg';

export default function PortfolioBuilder() {
  const {
    portfolioPhotos,
    portfolioVideoLinks,
    portfolioScripts,
    portfolioLink,
    portfolioBioCompleted,
    portfolioRateCardCompleted,
    portfolioStatement,
    ugcSelectedNiche,
    contentCategory,
    setField,
  } = useCampaignStore();

  const [linkSaved, setLinkSaved] = useState(false);
  const [tempLink, setTempLink] = useState(portfolioLink || '');
  const [copiedStatement, setCopiedStatement] = useState(false);
  const [zoomedImage, setZoomedImage] = useState<string | null>(null);

  const photosCount = portfolioPhotos.filter(p => p && p.url).length;
  const videosCount = portfolioVideoLinks.filter(v => v && v.link).length;
  const hasPortfolioStatement = portfolioScripts.length > 0;

  const checklistItems = [
    {
      id: 'photos',
      label: 'Portfolio photos',
      completed: photosCount > 0,
      detail: `${photosCount} photos uploaded`,
      link: 'ugc-portfolio-photos',
      linkText: photosCount === 0 ? 'Go to Portfolio Photos →' : null,
    },
    {
      id: 'videos',
      label: 'Portfolio videos',
      completed: videosCount > 0,
      detail: `${videosCount} videos added`,
      link: 'ugc-portfolio-videos',
      linkText: videosCount === 0 ? 'Go to Portfolio Videos →' : null,
    },
    {
      id: 'ratecard',
      label: 'Rate card',
      completed: portfolioRateCardCompleted,
      detail: portfolioRateCardCompleted ? 'Completed' : 'Not yet downloaded',
      link: 'ugc-rates',
      linkText: 'Go to Rate Card →',
    },
    {
      id: 'bio',
      label: 'Short bio',
      completed: portfolioBioCompleted,
      detail: portfolioBioCompleted ? 'Completed' : 'I have written a short bio about who I am and my niche',
      canToggle: true,
    },
    {
      id: 'statement',
      label: 'Portfolio statement',
      completed: hasPortfolioStatement,
      detail: hasPortfolioStatement ? 'Generated' : 'Not yet generated',
      link: 'ugc-portfolio-videos',
      linkText: !hasPortfolioStatement ? 'Go generate yours →' : null,
    },
  ];

  const completedCount = checklistItems.filter(item => item.completed).length;

  const getChecklistMessage = () => {
    if (completedCount <= 2) {
      return "You are not quite ready to organise yet — head back and complete your photos and videos first";
    } else if (completedCount <= 4) {
      return "Almost ready — finish the remaining items then come back to organise";
    } else {
      return "You are ready — let's get everything into one place";
    }
  };

  const handleSaveLink = () => {
    setField('portfolioLink', tempLink);
    setLinkSaved(true);
    setTimeout(() => setLinkSaved(false), 3000);
  };

  const handleToggleBio = () => {
    setField('portfolioBioCompleted', !portfolioBioCompleted);
  };

  const handleToggleRateCard = () => {
    setField('portfolioRateCardCompleted', !portfolioRateCardCompleted);
  };

  const hasFaceForward = portfolioVideoLinks.some(v => v && v.link && v.isFaceForward);
  const hasFaceless = portfolioVideoLinks.some(v => v && v.link && !v.isFaceForward);
  const niche = ugcSelectedNiche || contentCategory || '';

  const getAutoGeneratedStatement = () => {
    if (photosCount === 0 && videosCount === 0) {
      return 'Complete your portfolio photos and videos first — your statement will auto-generate here.';
    }

    const videoTypes = portfolioVideoLinks
      .filter(v => v && v.link && v.videoType)
      .map(v => v.videoType)
      .slice(0, 3)
      .join(', ');

    const portfolioLinkText = portfolioLink ? ` available at ${portfolioLink}` : '';

    if (hasFaceForward && hasFaceless) {
      return `I create both face forward and faceless UGC content specialising in ${videoTypes || 'authentic video content'}${niche ? ` for ${niche} brands` : ''}. My portfolio includes ${videosCount} videos and ${photosCount} photos${portfolioLinkText}.`;
    } else if (hasFaceless) {
      return `I specialise in faceless UGC content including voiceover and text on screen ads${niche ? ` for ${niche} brands` : ''}. My portfolio includes ${videosCount} videos and ${photosCount} photos${portfolioLinkText}.`;
    } else {
      return `I create face forward UGC content specialising in ${videoTypes || 'authentic video content'}${niche ? ` for ${niche} brands` : ''}. My portfolio includes ${videosCount} videos and ${photosCount} photos${portfolioLinkText}.`;
    }
  };

  useEffect(() => {
    const statement = getAutoGeneratedStatement();
    if (statement !== portfolioStatement) {
      setField('portfolioStatement', statement);
    }
  }, [photosCount, videosCount, portfolioLink, hasFaceForward, hasFaceless, niche]);

  const handleCopyStatement = () => {
    if (portfolioStatement) {
      navigator.clipboard.writeText(portfolioStatement);
      setCopiedStatement(true);
      setTimeout(() => setCopiedStatement(false), 2000);
    }
  };

  const hostingOptions = [
    {
      title: '🟢 Google Drive — Recommended for beginners',
      subtitle: 'Free, easy, works on any device',
      steps: [
        'Go to drive.google.com and sign in',
        'Click New → New Folder → name it "My UGC Portfolio"',
        'Inside create two subfolders: "Photos" and "Videos"',
        'Upload all your portfolio photos to the Photos folder',
        'Upload your videos or paste video file links into the Videos folder',
        'Right click the main portfolio folder → Share → Anyone with the link can view',
        'Copy the link — this is your portfolio link',
      ],
      buttonText: 'Open Google Drive →',
      link: 'https://drive.google.com',
    },
    {
      title: '🎨 Canva Portfolio — Recommended for visual impact',
      subtitle: 'Free, looks incredibly professional, great first impression',
      steps: [
        'Go to canva.com and create a free account',
        'Search "UGC Portfolio" or "Media Kit" in templates',
        'Add your best 5-10 photos directly into the template',
        'Add your video links as clickable buttons',
        'Add your name, niche, rates and contact details',
        'Click Share → Publish to Web to get your portfolio link',
        'Copy the link — this is your portfolio link',
      ],
      buttonText: 'Open Canva →',
      link: 'https://www.canva.com',
    },
    {
      title: '📦 Dropbox — Best for large video files',
      subtitle: 'Free up to 2GB, reliable for large video files',
      steps: [
        'Go to dropbox.com and create a free account',
        'Click Upload → select all your portfolio videos and photos',
        'Create a folder called "UGC Portfolio"',
        'Right click the folder → Share → Copy Link',
        'This is your portfolio link',
      ],
      buttonText: 'Open Dropbox →',
      link: 'https://www.dropbox.com',
    },
    {
      title: '🌐 Personal Website — Best for serious creators',
      subtitle: 'Most professional, fully branded, stands out from other creators',
      steps: [
        'Recommended: Wix, Squarespace, or Carrd at $19/year',
      ],
      buttonText: 'Try Carrd →',
      link: 'https://carrd.co',
    },
  ];

  return (
    <div style={{ paddingBottom: '120px' }}>
      <h1 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '42px', fontWeight: 600, color: '#f0ebff', marginBottom: '12px' }}>
        Organise Your Portfolio
      </h1>
      <p style={{ fontSize: '14px', color: '#9b8fb5', marginBottom: '32px' }}>
        Pull everything together into one clean professional link
      </p>

      <div
        style={{
          background: 'linear-gradient(135deg, rgba(201,168,76,0.15), rgba(139,105,20,0.1))',
          border: '2px solid rgba(201,168,76,0.3)',
          borderRadius: '12px',
          padding: '20px 24px',
          marginBottom: '32px',
        }}
      >
        <div style={{ fontSize: '16px', fontWeight: 700, color: '#e8c96a', marginBottom: '8px' }}>
          🗂️ You have your content — now make it sendable in one click
        </div>
        <p style={{ fontSize: '13px', color: '#d0c9e0', lineHeight: '1.6', margin: 0 }}>
          Your photos and videos are done. Now you need to organise everything into one clean professional link that you can send to any brand in seconds. This is the final step before you start pitching.
        </p>
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          Section 1 — Your Portfolio Checklist
        </h2>
        <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '24px' }}>
          Before you organise — make sure you have everything
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '24px' }}>
          {checklistItems.map((item) => (
            <div
              key={item.id}
              style={{
                background: item.completed ? 'rgba(34,197,94,0.08)' : 'rgba(255,255,255,0.03)',
                border: `1px solid ${item.completed ? 'rgba(34,197,94,0.3)' : 'rgba(255,255,255,0.1)'}`,
                borderRadius: '12px',
                padding: '16px 20px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: '16px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flex: 1 }}>
                {item.canToggle ? (
                  <button
                    onClick={item.id === 'bio' ? handleToggleBio : handleToggleRateCard}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      cursor: 'pointer',
                      padding: 0,
                    }}
                  >
                    {item.completed ? (
                      <CheckCircle2 size={24} style={{ color: '#22c55e' }} />
                    ) : (
                      <Circle size={24} style={{ color: '#9b8fb5' }} />
                    )}
                  </button>
                ) : (
                  item.completed ? (
                    <CheckCircle2 size={24} style={{ color: '#22c55e' }} />
                  ) : (
                    <Circle size={24} style={{ color: '#9b8fb5' }} />
                  )
                )}
                <div>
                  <div style={{ fontSize: '14px', fontWeight: 600, color: item.completed ? '#22c55e' : '#f0ebff', marginBottom: '2px' }}>
                    {item.label}
                  </div>
                  <div style={{ fontSize: '12px', color: '#9b8fb5' }}>
                    {item.detail}
                  </div>
                </div>
              </div>
              {item.linkText && (
                <button
                  onClick={() => {
                    const section = document.querySelector(`[data-section="${item.link}"]`);
                    if (section) {
                      section.scrollIntoView({ behavior: 'smooth' });
                    }
                  }}
                  style={{
                    padding: '8px 16px',
                    background: 'transparent',
                    border: '1px solid rgba(201,168,76,0.4)',
                    borderRadius: '100px',
                    color: '#c9a84c',
                    fontSize: '12px',
                    fontWeight: 600,
                    cursor: 'pointer',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {item.linkText}
                </button>
              )}
            </div>
          ))}
        </div>

        <div
          style={{
            background: completedCount === 5 ? 'rgba(34,197,94,0.12)' : 'rgba(201,168,76,0.12)',
            border: `2px solid ${completedCount === 5 ? 'rgba(34,197,94,0.3)' : 'rgba(201,168,76,0.3)'}`,
            borderRadius: '12px',
            padding: '16px 20px',
          }}
        >
          <div style={{ fontSize: '13px', color: '#d0c9e0', lineHeight: '1.6' }}>
            {getChecklistMessage()}
          </div>
        </div>
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          Section 2 — Choose Where To Host Your Portfolio
        </h2>
        <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '24px' }}>
          Pick one home for all your content. Brands want one link — not five. Choose one platform and keep everything there.
        </p>

        <div style={{ display: 'grid', gap: '20px' }}>
          {hostingOptions.map((option, index) => (
            <div
              key={index}
              style={{
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '12px',
                padding: '24px',
              }}
            >
              <h3 style={{ fontSize: '18px', fontWeight: 700, color: '#e8c96a', marginBottom: '4px' }}>
                {option.title}
              </h3>
              <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '16px' }}>
                {option.subtitle}
              </p>
              <div style={{ marginBottom: '20px' }}>
                <div style={{ fontSize: '12px', fontWeight: 600, color: '#f0ebff', marginBottom: '12px' }}>
                  Steps:
                </div>
                <ol style={{ margin: 0, paddingLeft: '20px' }}>
                  {option.steps.map((step, idx) => (
                    <li key={idx} style={{ fontSize: '13px', color: '#d0c9e0', marginBottom: '8px', lineHeight: '1.5' }}>
                      {step}
                    </li>
                  ))}
                </ol>
              </div>
              <a
                href={option.link}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '8px',
                  padding: '10px 20px',
                  background: 'linear-gradient(135deg, #c9a84c, #8B6914)',
                  color: '#0a0610',
                  border: 'none',
                  borderRadius: '100px',
                  fontSize: '13px',
                  fontWeight: 700,
                  textDecoration: 'none',
                  cursor: 'pointer',
                  boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
                }}
              >
                {option.buttonText}
                <ExternalLink size={14} />
              </a>
            </div>
          ))}
        </div>
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          Section 3 — Save Your Portfolio Link
        </h2>
        <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '24px' }}>
          Once you have set up your portfolio folder and copied your link paste it below. This link will automatically appear in your rate card, pitch templates and UGC Pack.
        </p>

        <div style={{ marginBottom: '16px' }}>
          <input
            type="url"
            value={tempLink}
            onChange={(e) => setTempLink(e.target.value)}
            placeholder="Paste your portfolio link here e.g. https://drive.google.com/your-portfolio"
            style={{
              width: '100%',
              padding: '14px 16px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '8px',
              color: '#f0ebff',
              fontSize: '14px',
              marginBottom: '12px',
            }}
          />
          <button
            onClick={handleSaveLink}
            disabled={!tempLink}
            style={{
              padding: '12px 24px',
              background: linkSaved ? 'rgba(34,197,94,0.2)' : 'linear-gradient(135deg, #c9a84c, #8B6914)',
              border: linkSaved ? '1px solid #22c55e' : 'none',
              borderRadius: '100px',
              color: linkSaved ? '#22c55e' : '#0a0610',
              fontSize: '14px',
              fontWeight: 700,
              cursor: tempLink ? 'pointer' : 'not-allowed',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
              opacity: tempLink ? 1 : 0.5,
            }}
          >
            {linkSaved ? (
              <>
                <CheckCircle2 size={16} />
                Portfolio Link Saved!
              </>
            ) : (
              'Save My Portfolio Link →'
            )}
          </button>
        </div>

        {portfolioLink && (
          <div
            style={{
              background: 'rgba(34,197,94,0.12)',
              border: '1px solid rgba(34,197,94,0.3)',
              borderRadius: '8px',
              padding: '12px 16px',
              fontSize: '12px',
              color: '#22c55e',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
            }}
          >
            <CheckCircle2 size={16} />
            Portfolio link saved — it will now appear automatically in your rate card, pitches and UGC Pack
          </div>
        )}
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          ✍️ Your Portfolio Statement
        </h2>
        <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '24px', fontStyle: 'italic' }}>
          A professional one-sentence summary of who you are as a creator. Paste this everywhere — your rate card, your pitches, your bio, your UGC Pack.
        </p>

        <div
          style={{
            background: 'rgba(255,255,255,0.03)',
            border: '1px solid rgba(255,255,255,0.1)',
            borderRadius: '8px',
            padding: '20px',
            marginBottom: '16px',
          }}
        >
          <p style={{ fontSize: '14px', color: '#d0c9e0', lineHeight: '1.7', margin: 0 }}>
            {portfolioStatement || getAutoGeneratedStatement()}
          </p>
        </div>

        {portfolioStatement && photosCount > 0 && videosCount > 0 ? (
          <button
            onClick={handleCopyStatement}
            style={{
              padding: '12px 24px',
              background: copiedStatement ? 'rgba(34,197,94,0.2)' : 'linear-gradient(135deg, #c9a84c, #8B6914)',
              border: copiedStatement ? '1px solid #22c55e' : 'none',
              borderRadius: '100px',
              color: copiedStatement ? '#22c55e' : '#0a0610',
              fontSize: '14px',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
              transition: 'all 0.2s',
            }}
          >
            {copiedStatement ? (
              <>
                <CheckCircle2 size={16} />
                Copied!
              </>
            ) : (
              <>
                <Copy size={16} />
                Copy My Portfolio Statement →
              </>
            )}
          </button>
        ) : (
          <div
            style={{
              background: 'rgba(201,168,76,0.08)',
              border: '1px solid rgba(201,168,76,0.2)',
              borderRadius: '8px',
              padding: '12px 16px',
              fontSize: '12px',
              color: '#c9a84c',
              fontStyle: 'italic',
            }}
          >
            Complete your portfolio photos and videos above — your statement will auto-generate when ready
          </div>
        )}
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          Section 4 — What Your Portfolio Folder Should Contain
        </h2>
        <p style={{ fontSize: '13px', color: '#9b8fb5', marginBottom: '24px' }}>
          The complete brand-ready portfolio checklist
        </p>

        <div
          style={{
            background: 'rgba(255,255,255,0.03)',
            border: '1px solid rgba(255,255,255,0.1)',
            borderRadius: '8px',
            padding: '20px',
            marginBottom: '20px',
          }}
        >
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            <li style={{ fontSize: '14px', color: '#d0c9e0', marginBottom: '12px', lineHeight: '1.5' }}>
              5-10 portfolio photos covering different photo types
            </li>
            <li style={{ fontSize: '14px', color: '#d0c9e0', marginBottom: '12px', lineHeight: '1.5' }}>
              5-10 portfolio videos covering different video formats
            </li>
            <li style={{ fontSize: '14px', color: '#d0c9e0', marginBottom: '12px', lineHeight: '1.5' }}>
              Your rate card PDF or PNG
            </li>
            <li style={{ fontSize: '14px', color: '#d0c9e0', marginBottom: '12px', lineHeight: '1.5' }}>
              A short bio: your name, niche, content style and contact details
            </li>
            <li style={{ fontSize: '14px', color: '#d0c9e0', marginBottom: 0, lineHeight: '1.5' }}>
              Your portfolio statement
            </li>
          </ul>
        </div>

        <div
          style={{
            background: 'rgba(201,168,76,0.08)',
            border: '1px solid rgba(201,168,76,0.2)',
            borderRadius: '8px',
            padding: '12px 16px',
            fontSize: '12px',
            color: '#c9a84c',
            fontStyle: 'italic',
            marginBottom: '24px',
          }}
        >
          Update your portfolio folder every time you create new content. A growing portfolio is a working portfolio.
        </div>

        <button
          onClick={() => {
            const section = document.querySelector('[data-section="ugc-pack"]');
            if (section) {
              section.scrollIntoView({ behavior: 'smooth' });
            }
          }}
          style={{
            padding: '14px 28px',
            background: 'linear-gradient(135deg, #c9a84c, #8B6914)',
            color: '#0a0610',
            border: 'none',
            borderRadius: '100px',
            fontSize: '15px',
            fontWeight: 700,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
          }}
        >
          <Folder size={18} />
          My Portfolio Is Ready — Go To UGC Pack →
        </button>
      </div>

      <div
        style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          padding: '32px',
          marginBottom: '32px',
        }}
      >
        <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: '28px', fontWeight: 600, color: '#f0ebff', marginBottom: '8px' }}>
          📐 What A Brand-Ready Portfolio Looks Like
        </h2>
        <p style={{ fontSize: '14px', color: '#9b8fb5', marginBottom: '32px' }}>
          These are real examples of professional UGC creator portfolios. Build yours in Canva using this structure.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '24px', marginBottom: '24px' }}>
          <div>
            <div
              onClick={() => setZoomedImage(portfolioTemplate1)}
              style={{
                position: 'relative',
                height: '600px',
                overflowY: 'auto',
                overflowX: 'hidden',
                background: 'rgba(255,255,255,0.03)',
                border: '2px solid #c9a84c',
                borderRadius: '12px',
                cursor: 'zoom-in',
                transition: 'transform 0.2s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'scale(1.02)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'scale(1)';
              }}
            >
              <img
                src={portfolioTemplate1}
                alt="Portfolio Template Example 1"
                style={{
                  width: '100%',
                  display: 'block',
                }}
              />
              <div
                style={{
                  position: 'absolute',
                  top: '12px',
                  right: '12px',
                  background: 'rgba(0,0,0,0.7)',
                  borderRadius: '50%',
                  padding: '8px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <ZoomIn size={20} style={{ color: '#c9a84c' }} />
              </div>
            </div>
            <p style={{ fontSize: '13px', color: '#9b8fb5', marginTop: '12px', textAlign: 'center', fontWeight: 600 }}>
              Portfolio Template Example 1
            </p>
          </div>

          <div>
            <div
              onClick={() => setZoomedImage(portfolioTemplate2)}
              style={{
                position: 'relative',
                height: '600px',
                overflowY: 'auto',
                overflowX: 'hidden',
                background: 'rgba(255,255,255,0.03)',
                border: '2px solid #c9a84c',
                borderRadius: '12px',
                cursor: 'zoom-in',
                transition: 'transform 0.2s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'scale(1.02)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'scale(1)';
              }}
            >
              <img
                src={portfolioTemplate2}
                alt="Portfolio Template Example 2"
                style={{
                  width: '100%',
                  display: 'block',
                }}
              />
              <div
                style={{
                  position: 'absolute',
                  top: '12px',
                  right: '12px',
                  background: 'rgba(0,0,0,0.7)',
                  borderRadius: '50%',
                  padding: '8px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <ZoomIn size={20} style={{ color: '#c9a84c' }} />
              </div>
            </div>
            <p style={{ fontSize: '13px', color: '#9b8fb5', marginTop: '12px', textAlign: 'center', fontWeight: 600 }}>
              Portfolio Template Example 2
            </p>
          </div>
        </div>

        <div
          style={{
            background: 'rgba(201,168,76,0.08)',
            border: '1px solid rgba(201,168,76,0.2)',
            borderRadius: '8px',
            padding: '16px 20px',
            fontSize: '13px',
            color: '#d0c9e0',
            lineHeight: '1.6',
            marginBottom: '24px',
          }}
        >
          Notice the structure — hero section at the top, videos and photos in grids, about me section and a clear contact call to action at the bottom. Follow this exact structure when building yours.
        </div>

        <button
          onClick={() => window.open('https://www.canva.com/templates/?query=ugc+portfolio', '_blank')}
          style={{
            padding: '14px 28px',
            background: 'linear-gradient(135deg, #c9a84c, #8B6914)',
            color: '#0a0610',
            border: 'none',
            borderRadius: '100px',
            fontSize: '15px',
            fontWeight: 700,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            boxShadow: '0 4px 16px rgba(201,168,76,0.4)',
          }}
        >
          <ExternalLink size={18} />
          Build Mine In Canva →
        </button>
      </div>

      {zoomedImage && (
        <div
          onClick={() => setZoomedImage(null)}
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0,0,0,0.95)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 9999,
            padding: '40px',
            cursor: 'zoom-out',
          }}
        >
          <button
            onClick={() => setZoomedImage(null)}
            style={{
              position: 'absolute',
              top: '20px',
              right: '20px',
              background: 'rgba(201,168,76,0.2)',
              border: '2px solid #c9a84c',
              borderRadius: '50%',
              padding: '12px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              zIndex: 10000,
            }}
          >
            <X size={24} style={{ color: '#c9a84c' }} />
          </button>
          <div
            style={{
              maxHeight: '90vh',
              maxWidth: '90vw',
              overflowY: 'auto',
              overflowX: 'auto',
              background: '#1a1625',
              borderRadius: '12px',
              border: '2px solid #c9a84c',
            }}
          >
            <img
              src={zoomedImage}
              alt="Portfolio Template"
              style={{
                display: 'block',
                maxWidth: '100%',
                height: 'auto',
              }}
            />
          </div>
        </div>
      )}
    </div>
  );
}
